"use client";

import { Bot, Cpu, TrendingDown, TrendingUp, Minus } from "lucide-react";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { StoredAnalysis } from "@/lib/ai/store";
import type { RowUsd } from "@/components/dashboard/live-signals-table";

export interface AiAnalysisDrawerProps {
  analysis: StoredAnalysis | null;
  /** Per-user USD TP/SL envelope for the selected row, when available. */
  usd?: RowUsd | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

function fmtUsd(n: number): string {
  if (!Number.isFinite(n)) return "—";
  return `$${n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function fmtPrice(n: number): string {
  if (!Number.isFinite(n)) return "—";
  // Adaptive precision for both large- and micro-cap prices.
  const digits = n >= 1 ? 2 : n >= 0.01 ? 4 : 8;
  return n.toLocaleString(undefined, {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}

const SENTIMENT_STYLES: Record<
  StoredAnalysis["ai"]["sentiment"],
  { label: string; className: string; Icon: typeof TrendingUp }
> = {
  BULLISH: {
    label: "BULLISH",
    className: "bg-emerald-500/15 text-emerald-400",
    Icon: TrendingUp,
  },
  BEARISH: {
    label: "BEARISH",
    className: "bg-rose-500/15 text-rose-400",
    Icon: TrendingDown,
  },
  NEUTRAL: {
    label: "NEUTRAL",
    className: "bg-white/10 text-muted-foreground",
    Icon: Minus,
  },
};

const RISK_STYLES: Record<StoredAnalysis["ai"]["riskLevel"], string> = {
  LOW: "bg-emerald-500/15 text-emerald-400",
  MEDIUM: "bg-amber-500/15 text-amber-400",
  HIGH: "bg-rose-500/15 text-rose-400",
};

/**
 * Modern AI analysis card: technical summary, entry/SL/TP levels with an R:R
 * badge, sentiment + risk tags, and a provenance badge (LLM vs deterministic).
 */
export function AiAnalysisDrawer({
  analysis,
  usd,
  open,
  onOpenChange,
}: AiAnalysisDrawerProps) {
  if (!analysis) return null;

  const { ai } = analysis;
  const sentiment = SENTIMENT_STYLES[ai.sentiment];
  const isLlm = analysis.source === "llm";
  const tp = ai.takeProfitLevels ?? [];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center justify-between gap-2 pr-6">
            <DialogTitle className="flex items-center gap-2 text-xl">
              {analysis.symbol}
              <span className="text-sm font-normal text-muted-foreground">
                {analysis.interval}
              </span>
            </DialogTitle>
            <Badge
              className={cn(
                "text-xs font-semibold",
                analysis.direction === "LONG"
                  ? "bg-emerald-500/15 text-emerald-400"
                  : "bg-rose-500/15 text-rose-400",
              )}
            >
              {analysis.direction}
            </Badge>
          </div>
        </DialogHeader>

        {/* Sentiment / risk / provenance */}
        <div className="flex flex-wrap items-center gap-2">
          <span
            className={cn(
              "inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold",
              sentiment.className,
            )}
          >
            <sentiment.Icon className="size-3.5" /> {sentiment.label}
          </span>
          <span
            className={cn(
              "inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold",
              RISK_STYLES[ai.riskLevel],
            )}
          >
            {ai.riskLevel} RISK
          </span>
          <span className="inline-flex items-center gap-1 rounded-full bg-white/5 px-2.5 py-1 text-xs text-muted-foreground">
            {isLlm ? (
              <>
                <Bot className="size-3.5" /> Generated by {analysis.model}
              </>
            ) : (
              <>
                <Cpu className="size-3.5" /> Technical Deterministic Engine
              </>
            )}
          </span>
        </div>

        {/* Technical summary */}
        <p className="text-sm leading-relaxed text-foreground/90">{ai.summary}</p>

        {/* Levels */}
        <div className="grid grid-cols-2 gap-3">
          <LevelCard
            label="Entry range"
            value={`${fmtPrice(ai.entryRange[0])} – ${fmtPrice(ai.entryRange[1])}`}
          />
          <LevelCard
            label="Stop-loss"
            value={fmtPrice(ai.stopLoss)}
            tone="down"
          />
          <LevelCard
            label="Take-profit 1"
            value={tp[0] != null ? fmtPrice(tp[0]) : "—"}
            tone="up"
          />
          <LevelCard
            label="Take-profit 2"
            value={tp[1] != null ? fmtPrice(tp[1]) : "—"}
            tone="up"
          />
        </div>

        {/* Per-user USD TP/SL — sized from the caller's leverage / R:R / tier
            balance (Req 7.1). Only shown when the feed supplied the envelope. */}
        {usd && (
          <div className="rounded-lg border border-white/10 bg-white/[0.03] p-3">
            <div className="mb-2 flex items-center justify-between text-[11px] uppercase tracking-wide text-muted-foreground">
              <span>USD outcome</span>
              <span className="normal-case">
                {usd.leverage}x · {usd.rrRatio} · {fmtUsd(usd.balanceUsd)} base
              </span>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <LevelCard label="Stop-loss" value={fmtUsd(usd.stopLossUsd)} tone="down" />
              <LevelCard label="TP1" value={fmtUsd(usd.tp1Usd)} tone="up" />
              <LevelCard label="TP2" value={fmtUsd(usd.tp2Usd)} tone="up" />
            </div>
          </div>
        )}

        {/* R:R + score */}
        <div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[0.03] px-4 py-3">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            Risk : Reward
            <Badge variant="secondary" className="font-mono">
              {analysis.riskRewardRatio}
            </Badge>
          </div>
          <div className="text-sm text-muted-foreground">
            Score{" "}
            <span className="font-semibold tabular-nums text-foreground">
              {analysis.score.toFixed(0)}
            </span>
          </div>
        </div>

        {/* Key factors */}
        {ai.keyFactors?.length > 0 && (
          <div>
            <p className="mb-1.5 text-xs font-medium uppercase text-muted-foreground">
              Key factors
            </p>
            <ul className="flex flex-wrap gap-1.5">
              {ai.keyFactors.map((factor, i) => (
                <li key={i}>
                  <Badge variant="outline" className="font-normal">
                    {factor}
                  </Badge>
                </li>
              ))}
            </ul>
          </div>
        )}

        <p className="text-[11px] text-muted-foreground">
          Pattern: {analysis.pattern} · Not financial advice.
        </p>
      </DialogContent>
    </Dialog>
  );
}

function LevelCard({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone?: "up" | "down";
}) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2.5">
      <p className="text-[11px] uppercase tracking-wide text-muted-foreground">
        {label}
      </p>
      <p
        className={cn(
          "mt-0.5 font-mono text-sm font-semibold tabular-nums",
          tone === "up" && "text-emerald-400",
          tone === "down" && "text-rose-400",
        )}
      >
        {value}
      </p>
    </div>
  );
}
