// ---------------------------------------------------------------------------
// POST /api/analysis/scan — on-demand market scan (PRO only).
//
// Runs a full scan pass in-process (reading the shared Redis windows + the same
// analysis engine the worker uses), so Pro users can force an immediate refresh
// instead of waiting for the next automatic scan cadence. Free users are
// blocked with HTTP 403 (upgrade required); their feed is the shared 15m
// broadcast, regenerated by the worker.
// ---------------------------------------------------------------------------

import { NextResponse } from "next/server";

import { auth } from "@/auth";
import { getUserPlan } from "@/lib/user-entitlement";
import { getUserPreferences } from "@/lib/user-preferences";
import { scanMarket } from "@/lib/market/scan";
import { readProAnalysesByIntervals } from "@/lib/ai/store";
import { pushScanHistory } from "@/lib/market/redis-pipeline";
import { INTERVALS, type Interval } from "@/lib/market/types";
import { randomUUID } from "node:crypto";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Guard against abuse / overlapping heavy scans across requests.
let scanInFlight = false;
let lastScanAt = 0;
const MIN_SCAN_GAP_MS = 5_000;

export async function POST() {
  const session = await auth();
  const userId = session?.user?.id;
  if (!userId) {
    return NextResponse.json(
      { ok: false, error: "Authentication required." },
      { status: 401 },
    );
  }

  const plan = await getUserPlan(userId);
  if (plan !== "pro") {
    return NextResponse.json(
      {
        ok: false,
        error: "Upgrade to Pro to run manual scans.",
        upgradeRequired: true,
      },
      { status: 403 },
    );
  }

  const now = Date.now();
  if (scanInFlight || now - lastScanAt < MIN_SCAN_GAP_MS) {
    return NextResponse.json(
      { ok: false, error: "A scan is already running. Try again shortly." },
      { status: 429 },
    );
  }

  scanInFlight = true;
  try {
    // Pull fresh candles via REST so a manual scan reflects the live market
    // (the web container reaches Binance REST even where the WS is blocked).
    // Manual scan: fresh REST candles + bypass the Pro cooldown, and await AI
    // generation so the returned/stored analyses reflect this scan (not cached).
    const result = await scanMarket({
      trigger: "manual",
      refreshViaRest: true,
      ignoreCooldown: true,
    });
    lastScanAt = Date.now();

    // Return the caller's active-interval analyses so the UI can refresh
    // immediately (matches the /api/analysis/feed Pro shape).
    const prefs = await getUserPreferences(userId);
    const engineIntervals = new Set<Interval>(INTERVALS);
    const activeIntervals = prefs.intervals.filter((i): i is Interval =>
      engineIntervals.has(i as Interval),
    );
    // Pro sees the full top-movers set (favorites pinned first).
    const all = await readProAnalysesByIntervals(activeIntervals);
    const favoriteSet = new Set(
      prefs.favoritePairs.map((s) => s.toUpperCase()),
    );
    const analyses = [...all].sort((a, b) => {
      const aFav = favoriteSet.has(a.symbol.toUpperCase()) ? 1 : 0;
      const bFav = favoriteSet.has(b.symbol.toUpperCase()) ? 1 : 0;
      if (aFav !== bFav) return bFav - aFav;
      return b.score - a.score;
    });

    // Persist this manual scan to the user's history for later review.
    const entry = {
      id: randomUUID(),
      scannedAt: result.finishedAt,
      trigger: "manual" as const,
      symbolsScanned: result.symbolsScanned,
      combosScanned: result.combosScanned,
      candidatesFound: result.candidates.length,
      analyses,
    };
    await pushScanHistory(userId, entry).catch(() => {
      /* history is best-effort; never fail the scan on it */
    });

    return NextResponse.json({
      ok: true,
      id: entry.id,
      scannedAt: result.finishedAt,
      symbolsScanned: result.symbolsScanned,
      combosScanned: result.combosScanned,
      // Total candidates found market-wide across ALL timeframes.
      candidatesFound: result.candidates.length,
      // How many match the user's active timeframe(s) — i.e. what the table
      // actually shows. This is `analyses.length`.
      matchedForUser: analyses.length,
      activeIntervals,
      analyses,
    });
  } catch (e) {
    return NextResponse.json(
      { ok: false, error: e instanceof Error ? e.message : "Scan failed." },
      { status: 500 },
    );
  } finally {
    scanInFlight = false;
  }
}
